### ISSUE TITLE
Standalone language server (LSP)

### ISSUE THREAD

**Issue by thomasaarholt** [fivetran/dbt-language-server#1194]
Hello!
Is it possible to use dbt-language-server as a standalone language server according to the [language server protocol spec](https://microsoft.github.io/language-server-protocol/)? I would very much like to use this with helix (a vim-like text editor), in the same way that I use e.g. pyright.

**Comment by pgrivachev** [comment]
Hello @thomasaarholt!

We use language server protocol for communication between the client and server parts. In theory it should be possible to use dbt language server with other editors that support LSP, but I haven't tried it yet. Could you explain how do you use pyright or any other language server in helix?

**Comment by thomasaarholt** [comment]
Sure! Today I use pyright to highlight code and type errors as well as navigation like "go to function definition". One installs the language server (something like `brew install pyright`), and then adds a configuration like what is shown here for helix/pyright: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#python---pyright

Whenever I do something in helix, pyright is called according to the config: `pyright-langserver --stdio <some lsp command here>`.

**Comment by pgrivachev** [comment]
Hey @thomasaarholt! Thank you for detailed explanation. 

I prepared npm package for dbt-language-server. And it can be used for helix. But not all features will work as in VS Code. We recommend using autosave in VS Code. So all changes in extension are happen after file save event.

I tested this and it looks like go to definition, errors highlighting, SQL to ref conversion features work.

First you need to install dbt-language-server npm package:
```
npm install -g @fivetrandevelopers/dbt-language-server
```
Then you can check the version of the package (0.30.2 today):
```
dbt-language-server --version
```
To use it in helix the following `~/.config/helix/languages.toml` config should work:
```toml
[[language]]
name = "sql"
scope = "source.sql"
file-types = ["sql"]
roots = ["dbt_project.yml"]
language-server = { command = "dbt-language-server", args = ["--stdio"]}
config = { pythonInfo = { path = 'python' }, lspMode = 'dbtProject', enableSnowflakeSyntaxCheck = true }
```


https://github.com/fivetran/dbt-language-server/assets/3650304/7f2d60be-509f-4b9f-9ce1-4c7019c3166e

**Comment by thomasaarholt** [comment]
This is incredible!! It worked out of the box for the current release version of helix! Thank you SO much for this!

In case anyone wants to try, here is the equivalent config for the latest master (the configuration changed a bit):
```toml
[[language]]
name = "sql"
scope = "source.sql"
file-types = ["sql"]
roots = ["dbt_project.yml"]
language-servers = ["dbt-language-server"]

[language-server.dbt-language-server]
command = "dbt-language-server"
args = ["--stdio"]
config = { pythonInfo = { path = 'python' }, lspMode = 'dbtProject', enableSnowflakeSyntaxCheck = true }
```
