### ISSUE TITLE
Environment Variables in Profile not recognized

### ISSUE THREAD

**Issue by mattppal** [fivetran/dbt-language-server#604]
```
[0m14:08:08  Encountered an error:
Parsing Error
  Env var required but not provided: 'REDSHIFT_USER'
Wizard for dbt Core (TM)
```

Where profiles.yml contains:

```
underline_dbt:
  target: global
  
  outputs:
    global:
      user: "{{ env_var('REDSHIFT_USER') }}"
```

I'm setting variables in the vscode terminal, so I'm unsure why they aren't being recognized.
